### ISSUE TITLE
test pretrained model failed

### ISSUE THREAD

**Issue by yanqiangmiffy** [qizhex/RACE_AR_baselines#3]
```
 [root@localhost src]# bash test_GA.sh 
!!!test
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu1 is not available  (error: cuda unavailable)
/root/.pyenv/versions/yan35/lib/python3.5/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
06-27 16:35 main.py -train_file ../data/data/train -dev_file ../data/data/test -embedding_size 100 -pre_trained ../obj/model_GA.pkl.gz -test_only True -model GA -num_GA_layers 1 -hidden_size 128
06-27 16:35 --------------------------------------------------
06-27 16:35 Load data files..
06-27 16:35 ********** Train
06-27 16:35 #Examples: 87866
06-27 16:35 ********** Dev
06-27 16:35 #Examples: 4934
06-27 16:35 --------------------------------------------------
06-27 16:35 Build dictionary..
06-27 16:35 --------------------------------------------------
06-27 16:35 Embeddings: 50002 x 100
06-27 16:35 Compile functions..
Traceback (most recent call last):
  File "main.py", line 309, in <module>
    main(args)
  File "main.py", line 216, in main
    train_fn, test_fn, params, all_params = build_fn(args, embeddings)
  File "main.py", line 82, in build_fn
    rnn_layer=args.rnn_layer)
  File "/root/yanqiang/12-RACE_AR_baselines/src/nn_layers.py", line 87, in stack_rnn
    network = _rnn(True, name)
  File "/root/yanqiang/12-RACE_AR_baselines/src/nn_layers.py", line 84, in _rnn
    name=name + '_layer' + str(layer + 1))
  File "/root/.pyenv/versions/yan35/lib/python3.5/site-packages/lasagne/layers/recurrent.py", line 1180, in __init__
    super(GRULayer, self).__init__(incomings, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'only_return_final'
```
I tried to run test_GA.sh,but it failed,can you tell me what caused this?

**Comment by yanqiangmiffy** [comment]
Lasage should be 0.2.dev1
